In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
train = pd.read_csv("./data/train.csv", sep="###__###",header = None)
test = pd.read_csv("./data/test.csv", sep="###__###",header = None)

In [2]:
train.columns = ['ID', 'Age', 'Gender', 'Education', 'Query_List']
train.head()

,ID,Age,Gender,Education,Query_List
0,22DD920316420BE2DF8D6EE651BA174B,1,1,4,鏌斿拰鍙屾矡\t濂崇敓\t涓�璐㈢綉棣栭〉 璐㈢粡\thttp://pan.baidu.co...
1,43CC3AF5A8D6430A3B572337A889AFE4,2,1,3,"骞垮窞鍘ㄥ疂鐑ょ��\t涓栨儏钖�,浜烘儏鎭�,闆ㄩ�侀粍鏄忚姳鏄撹惤,鏅撻�庡共,娉�鐥�..."
2,E97654BFF5570E2CCD433EA6128EAC19,4,1,0,閽荤煶涔嬫唱鑰虫満\t鐩橀敠鍒版矆闃�\t鏃呴『鍏�浜�\t杈藉畞闃滄柊杞︾墝\tbaidu...
3,6931EFC26D229CCFCEA125D3F3C21E57,4,2,3,鏈�鍙楁�㈣繋鐙楃嫍鎺掕�屾��\t鑸舵�庝箞璇�\t鍦烘櫙鎻� 鍐欒寖渚�\t涓夌淮缁樺浘...
4,E780470C3BB0D340334BD08CDCC3C71A,2,2,4,骞叉Ы鐥囪兘鑷�鎰堝悧\t澶�澶�涓囧瞾鍙惰垝蹇冨幓娌″幓缇庡浗\t骞叉Ы鐥�\t鍙崇溂鐨�...

In [3]:
test.columns = ['ID', 'Query_List']
test.head()

,ID,Query_List
0,ED89D43B9F602F96D96C25255F7C228C,闄堝�﹀啲灏嗗嚭鐨勪綔鍝�\t鍒樻槉鐒朵笌璋�鏉鹃煹\t211瀛︽牎鐨勫垎鏁扮嚎\t璋佸敱鐨...
1,83C3B7B4AAF8074655A8079F561A76D6,e鐨�0.0052娆℃柟\tqq鎬庝箞蹇�閫熸彁鐜�\t缁濊壊鍊惧煄椋炵儫\t椹�鍏嬫�濅富...
2,CA9F675A024FB2353849350A35CF8B0F,榛戞殫鏂�\tlpl澶忓�ｈ禌\t澶у瘜璞�鐢电帺鍩�\t鑻遍泟鑱旂洘涔嬬數绔炵О鐜�\t鎵...
3,DE45B5C4E57AAEBCF3FDFA2A774093BF,涓�绉嬫按搴撻挀楸�\t楸肩��\t鐢ㄨ毌铓撻挀楸兼�庢牱璋冩紓\t浼犵粺閽�\t3鍙烽奔閽...
4,406A681FB3DF81EC0E561796AE50AE50,鍙风爜鍚夊嚩\t閫�浼戝共閮ㄦ�诲悗閰嶅伓\t閮�鍘挎湁鍝�浜涘ぇ瀛�\t鑳滃埄娌圭敯灞炰簬...

In [9]:

test_Nodup=test.drop_duplicates()
test_Nodup=test.dropna()
test_Nodup.head()

,ID,Query_List
0,ED89D43B9F602F96D96C25255F7C228C,闄堝�﹀啲灏嗗嚭鐨勪綔鍝�\t鍒樻槉鐒朵笌璋�鏉鹃煹\t211瀛︽牎鐨勫垎鏁扮嚎\t璋佸敱鐨...
1,83C3B7B4AAF8074655A8079F561A76D6,e鐨�0.0052娆℃柟\tqq鎬庝箞蹇�閫熸彁鐜�\t缁濊壊鍊惧煄椋炵儫\t椹�鍏嬫�濅富...
2,CA9F675A024FB2353849350A35CF8B0F,榛戞殫鏂�\tlpl澶忓�ｈ禌\t澶у瘜璞�鐢电帺鍩�\t鑻遍泟鑱旂洘涔嬬數绔炵О鐜�\t鎵...
3,DE45B5C4E57AAEBCF3FDFA2A774093BF,涓�绉嬫按搴撻挀楸�\t楸肩��\t鐢ㄨ毌铓撻挀楸兼�庢牱璋冩紓\t浼犵粺閽�\t3鍙烽奔閽...
4,406A681FB3DF81EC0E561796AE50AE50,鍙风爜鍚夊嚩\t閫�浼戝共閮ㄦ�诲悗閰嶅伓\t閮�鍘挎湁鍝�浜涘ぇ瀛�\t鑳滃埄娌圭敯灞炰簬...

In [10]:
train_Nodup=train.drop_duplicates()
train_Nodup=train.dropna()
train_Nodup.head()

,ID,Age,Gender,Education,Query_List
0,22DD920316420BE2DF8D6EE651BA174B,1,1,4,鏌斿拰鍙屾矡\t濂崇敓\t涓�璐㈢綉棣栭〉 璐㈢粡\thttp://pan.baidu.co...
1,43CC3AF5A8D6430A3B572337A889AFE4,2,1,3,"骞垮窞鍘ㄥ疂鐑ょ��\t涓栨儏钖�,浜烘儏鎭�,闆ㄩ�侀粍鏄忚姳鏄撹惤,鏅撻�庡共,娉�鐥�..."
2,E97654BFF5570E2CCD433EA6128EAC19,4,1,0,閽荤煶涔嬫唱鑰虫満\t鐩橀敠鍒版矆闃�\t鏃呴『鍏�浜�\t杈藉畞闃滄柊杞︾墝\tbaidu...
3,6931EFC26D229CCFCEA125D3F3C21E57,4,2,3,鏈�鍙楁�㈣繋鐙楃嫍鎺掕�屾��\t鑸舵�庝箞璇�\t鍦烘櫙鎻� 鍐欒寖渚�\t涓夌淮缁樺浘...
4,E780470C3BB0D340334BD08CDCC3C71A,2,2,4,骞叉Ы鐥囪兘鑷�鎰堝悧\t澶�澶�涓囧瞾鍙惰垝蹇冨幓娌″幓缇庡浗\t骞叉Ы鐥�\t鍙崇溂鐨�...

In [1]:
import re
import warnings
warnings.filterwarnings("ignore")
import pandas as pd


Path_train = "./data/train.csv"
Path_test = "./data/test.csv"
lab="###__###"

train = pd.read_csv(Path_train, sep = lab, header = None, encoding = 'utf-8')
test = pd.read_csv(Path_test, sep = lab, header = None, encoding = 'utf-8')

train.columns = ['ID', 'Age', 'Gender', 'Education', 'Query_List']
test.columns = ['ID', 'Query_List']


train_Nodup = train.drop_duplicates()
train_Nodup = train.dropna()

test_Nodup = test.drop_duplicates()
test_Nodup = test.dropna()

In [2]:
import re


def Del_web1(data):
    web = re.compile(r'[http|https]*://[a-zA-Z0-9.?/&=:]*', re.S)
    data = re.sub(web, " ", data)
    return data.strip()

def Del_web2(data):
    web = re.compile("ｗｗｗ\．|www\.|\.com", re.I)
    data = re.sub(web, " ", data)
    return data.strip()


train_Nodup['Query_List'] = train_Nodup['Query_List'].apply(lambda x: Del_web1(x))
train_Nodup['Query_List'] = train_Nodup['Query_List'].apply(lambda x: Del_web2(x))

test_Nodup['Query_List'] = test_Nodup['Query_List'].apply(lambda x: Del_web1(x))
test_Nodup['Query_List'] = test_Nodup['Query_List'].apply(lambda x: Del_web2(x))

train_Nodup['Query_List'].head(1)

0    柔和双沟\t女生\t中财网首页 财经\t \t周公解梦大全查询2345\t曹云金再讽郭德纲\...
Name: Query_List, dtype: object

In [3]:
train_Nodup.to_csv("./data/processed_train.csv", header = None, encoding='utf-8')
#test_Nodup.to_csv("./data/processed_test.csv", header = None, encoding='utf-8')

In [ ]:
import jieba
import warnings
warnings.filterwarnings("ignore")
import pandas as pd

jieba.enable_paddle()# 启动paddle模式

Pd_train = pd.read_csv("./data/processed_train.csv", header = None, encoding='utf-8')
Pd_test = pd.read_csv("./data/processed_test.csv", header = None, encoding='utf-8')

file_stoppath = "./Data/stopwords.txt"

stopwords=pd.read_csv(file_stoppath,index_col=False,quoting=3,sep="\t",names=['stopword'], encoding='utf-8')
stopwords=stopwords['stopword'].values
def process_df_text(content_lines):       
    segs=jieba.lcut(content_lines)
    segs = list(filter(lambda x:len(x)>1, segs)) #没有解析出来的新闻过滤掉
    segs = list(filter(lambda x:x not in stopwords, segs)) #把停用词过滤掉
    return (" ".join(segs))

In [ ]:
from sklearn.metrics import f1_score
from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone, BaseEstimator, TransformerMixin

class stratified_cross_val_score(BaseEstimator, TransformerMixin):
    """实现基于分层抽样的k折交叉验证"""
    
    def __init__(self, model, data, labels, random_state=0, cv=5):
        """
        :model: 训练的模型（回归或分类）
        :data: 只含特征值的完整数据集
        :labels: 只含标签值的完整数据集
        :random_state: 模型的随机种子值
        :cv: 交叉验证的次数
        """
        self.model = model
        self.data = data
        self.labels = labels
        self.random_state = random_state
        self.cv = cv
        self.score = []  # 储存每折测试集的模型评分
        self.i = 0            
    
    def fit(self, X, y):
        """
        :param X: 含有特征值和聚类结果的完整数据集
        :param y: 含有聚类结果的完整数据集
        """
        skfolds = StratifiedKFold(n_splits=self.cv, random_state=self.random_state)

        for train_index, test_index in skfolds.split(X, y):
            # 复制要训练的模型（分类或回归）
            clone_model = clone(self.model)
            strat_X_train_folds = self.data.loc[train_index]
            strat_y_train_folds = self.labels.loc[train_index]
            strat_X_test_fold = self.data.loc[test_index]
            strat_y_test_fold = self.labels.loc[test_index]
            
            # 训练模型
            clone_model.fit(strat_X_train_folds, strat_y_train_folds)
            # 预测值（这里是分类模型的分类结果）
            test_labels_pred = clone_model.predict(strat_X_test_fold)
            
            # 这里使用的是分类模型用的F1值，如果是回归模型可以换成相应的模型
            score_fold = f1_score(labels.loc[test_index], test_labels_pred, average="weighted")
            
            # 避免重复向列表里重复添加值
            if self.i < self.cv:
                self.score.append(score_fold)
            else:
                None
                
            self.i += 1
    
    def transform(self, X, y=None):
        return self
    
    def mean(self):
        """返回交叉验证评分的平均值"""
        return np.array(self.score).mean()
    
    def std(self):
        """返回交叉验证评分的标准差"""

In [ ]:
from sklearn.linear_model import SGDClassifier

# 分类模型
clf_model = SGDClassifier(max_iter=5, tol=-np.infty, random_state=42)
# 基于分层抽样的交叉验证，data是只含特征值的完整数据集，labels是只含标签值的完整数据集
clf_cross_val = stratified_cross_val_score(clf_model, data, labels, cv=5, random_state=42)
# data2是含有特征值和聚类结果的完整数据集
clf_cross_val.fit(data2, data2["Query_List"])